[package]
name = "rust-monty-parallel"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
subtle = "2.4"
rayon = { version = "1.6", optional = true }

[features]
parallel = ["rayon"]
default = []

[dev-dependencies]
criterion = "0.4"
